export const gêneros = ['Ação', 'Animação', 'Aventura', 'Comédia', 'Drama', 'Família', 'Fantasia', 'Faroeste', 'Guerra', 'Mistério', 'Musical', 'Romance', 'Suspense'];

export const filmes = [{ título: "O Circo", ano: "1928", gêneros: ["Comédia", "Família", "Romance"], sinopse: "O vagabundo Carlitos é confundido com um ladrão e vai se refugiar num circo, onde se transforma na atração principal e revolta-se contra o tirânico proprietário do circo.", imagem: "https://m.media-amazon.com/images/M/MV5BN2M4ZWMyNmUtNjI3My00NDE3LThmZjgtMDgzNTU2NGFjZWJmXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_.jpg", referência: "https://www.imdb.com/pt/title/tt0018773/" },
  { título: "Tempos Modernos", ano: "1936", gêneros: ["Comédia", "Drama", "Romance"], sinopse: "Um vagabundo luta para viver na sociedade industrial moderna com a ajuda de uma jovem.", imagem: "https://m.media-amazon.com/images/M/MV5BYzk1MDkxMWUtMTFmYS00YzA0LWE1YjctZjAxNjUwZTJkNTZkXkEyXkFqcGdeQXVyMDUyOTUyNQ@@._V1_.jpg", referência: "https://www.imdb.com/pt/title/tt0027977/" },
  { título: "Branca de Neve e os Sete Anões", ano: "1937", gêneros: ["Animação", "Aventura", "Família", "Romance", "Fantasia", "Musical"], sinopse: "Deixada numa floresta perigosa por sua madrasta malvada, uma princesa é resgatada por sete mineiros anões que a fazem parte de sua casa.", imagem: "https://m.media-amazon.com/images/M/MV5BNWQ4N2I1MzctNGU2YS00YzYyLTgyNmEtMTliZTQ5MGYxYzlkXkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_.jpg", referência: "https://www.imdb.com/pt/title/tt0029583/" },
  { título: "...E o Vento Levou", ano: "1939", gêneros: ["Drama", "Romance", "Guerra"], sinopse: "Uma mulher manipuladora e uma truhan embarcam em um romance turbulento durante a Guerra Civil Americana e o período da Reconstrução.", imagem: "https://m.media-amazon.com/images/M/MV5BYjUyZWZkM2UtMzYxYy00ZmQ3LWFmZTQtOGE2YjBkNjA3YWZlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg", referência: "https://www.imdb.com/pt/title/tt0031381/" },
  { título: "No Tempo das Diligências", ano: "1939", gêneros: ["Aventura", "Drama", "Faroeste"], sinopse: "Um grupo de pessoas que viajam por uma diligência acham sua jornada complicada pela ameaça de Geronimo, mas conseguem aprender alguma coisa sobre cada uma delas no processo.", imagem: "https://m.media-amazon.com/images/M/MV5BYmRiMGVhYmQtMzVhZi00NGI3LTg1OTItYWM2NzA5YzI4NDE1XkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_.jpg", referência: "https://www.imdb.com/pt/title/tt0031971/" },
  { título: "O Grande Ditador", ano: "1940", gêneros: ["Comédia", "Drama", "Guerra"], sinopse: "O ditador Hynkel tenta expandir seu império enquanto um pobre barbeiro judeu tenta evitar a perseguição do regime de Hynkel.", imagem: "https://m.media-amazon.com/images/M/MV5BMmExYWJjNTktNGUyZS00ODhmLTkxYzAtNWIzOGEyMGNiMmUwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg", referência: "https://www.imdb.com/pt/title/tt0032553/" },
  { título: "Dumbo", ano: "1941", gêneros: ["Animação", "Aventura", "Drama", "Família", "Fantasia", "Musical"], sinopse: "Ridicularizado por suas enormes orelhas, um jovem elefante de circo é auxiliado por um rato a alcançar todo o seu potencial.", imagem: "https://m.media-amazon.com/images/M/MV5BMmU1NjQ3YjktZGMxYS00N2IwLTllZWQtOGNjYWE4MzgxNzk2XkEyXkFqcGdeQXVyODU2MDg1NzU@._V1_.jpg", referência: "https://www.imdb.com/pt/title/tt0033563/" },
  { título: "Casablanca", ano: "1942", gêneros: ["Drama", "Romance", "Guerra"], sinopse: "O proprietário cético de uma boate protege um antigo amor e seu marido dos nazistas no Marrocos.", imagem: "https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", referência: "https://www.imdb.com/pt/title/tt0034583/" },
  { título: "O Tesouro da Sierra Madre", ano: "1948", gêneros: ["Aventura", "Drama", "Faroeste"], sinopse: "Dois americanos em busca de trabalho no México convencem um homem a ajudá-los a extrair ouro nas montanhas da Serra Madre.", imagem: "https://m.media-amazon.com/images/M/MV5BOTJlZWMxYzEtMjlkMS00ODE0LThlM2ItMDI3NGQ2YjhmMzkxXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_.jpg", referência: "https://www.imdb.com/pt/title/tt0040897/" },
  { título: "A Malvada", ano: "1950", gêneros: ["Drama"], sinopse: "Uma ingênua se insinua na vida de uma atriz de teatro, e de seu círculo de amigas de teatro.", imagem: "https://m.media-amazon.com/images/M/MV5BOTM4ZjUzOGUtYzdlZi00ZmM5LTk5NTEtMjQxNDVmOTc5NWNlXkEyXkFqcGc@._V1_FMjpg_UY2260_.jpg", referência: "https://www.imdb.com/pt/title/tt0042192/" },
  { título: "Matar ou Morrer", ano: "1952", gêneros: ["Drama", "Suspense", "Faroeste"], sinopse: "Apesar dos desentendimentos com sua namorada e os habitantes da cidade, um marechal deve enfrentar uma gangue quando seu líder chegar no trem do meio-dia.", imagem: "https://m.media-amazon.com/images/M/MV5BOWIzZGUxZmItOThkMS00Y2QxLTg0MTYtMDdhMjRlNTNlYTI3L2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_.jpg", referência: "https://www.imdb.com/pt/title/tt0044706/" },
  { título: "Os Sete Samurais", ano: "1954", gêneros: ["Ação", "Drama"], sinopse: "Uma aldeia pobre sob a ameaça de bandidos recruta sete samurais para ajudá-los a se defenderem.", imagem: "https://m.media-amazon.com/images/M/MV5BNTkwY2I5NWMtMjNlNi00ZThjLWI4NzQtNDI4M2I4OGM1YjAzXkEyXkFqcGdeQXVyNzYxODE3NTQ@._V1_.jpg", referência: "https://www.imdb.com/pt/title/tt0047478/" },
  { título: "Janela Indiscreta", ano: "1954", gêneros: ["Drama", "Mistério", "Suspense"], sinopse: "Um fotógrafo em uma cadeira de rodas espiona seus vizinhos pela janela de seu apartamento e está convencido de que um deles cometeu um assassinato.", imagem: "https://m.media-amazon.com/images/M/MV5BMjE4YjMxZGEtYTBmMi00OTQwLThjN2EtN2Y0ZGJjMmMxOWM4XkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_.jpg", referência: "https://www.imdb.com/pt/title/tt0047396/" } ];